package finance;

import model.MarketState;
import model.SimulationScenario;

import java.util.List;
import java.util.Objects;

/**
 * Computes portfolio profit and loss (P&L)
 * from simulated market scenarios.
 *
 * <p>For a scenario m, P&L is defined as:</p>
 *
 * <pre>
 * PnL_m = V_T(m) - V_0
 * </pre>
 *
 * where V_0 is the initial portfolio value and V_T(m)
 * is the portfolio value under scenario m.
 */
public final class PnLCalculator {

    private final PortfolioPricer portfolioPricer;

    /**
     * Creates a P&L calculator.
     *
     * @param portfolioPricer portfolio valuation service
     * @throws NullPointerException if portfolioPricer is null
     */
    public PnLCalculator(PortfolioPricer portfolioPricer) {
        this.portfolioPricer = Objects.requireNonNull(
                portfolioPricer,
                "portfolioPricer must not be null"
        );
    }

    /**
     * Computes the P&L of a portfolio for one simulation scenario.
     *
     * @param portfolio portfolio being evaluated
     * @param initialState initial market state
     * @param scenario future simulation scenario
     * @return scenario P&L
     */
    public double calculate(
            Portfolio portfolio,
            MarketState initialState,
            SimulationScenario scenario) {

        Objects.requireNonNull(
                portfolio,
                "portfolio must not be null"
        );

        Objects.requireNonNull(
                initialState,
                "initialState must not be null"
        );

        Objects.requireNonNull(
                scenario,
                "scenario must not be null"
        );

        double initialValue =
                portfolioPricer.value(
                        portfolio,
                        initialState
                );

        double futureValue =
                portfolioPricer.value(
                        portfolio,
                        scenario.getTerminalState()
                );

        return futureValue - initialValue;
    }

    /**
     * Computes the P&L distribution generated by multiple
     * simulation scenarios.
     *
     * @param portfolio portfolio being evaluated
     * @param initialState initial market state
     * @param scenarios simulation scenarios
     * @return P&L values in the same order as the scenarios
     *
     * @throws NullPointerException if an argument or scenario is null
     * @throws IllegalArgumentException if scenarios is empty
     */
    public double[] calculateDistribution(
            Portfolio portfolio,
            MarketState initialState,
            List<SimulationScenario> scenarios) {

        Objects.requireNonNull(
                portfolio,
                "portfolio must not be null"
        );

        Objects.requireNonNull(
                initialState,
                "initialState must not be null"
        );

        Objects.requireNonNull(
                scenarios,
                "scenarios must not be null"
        );

        if (scenarios.isEmpty()) {
            throw new IllegalArgumentException(
                    "scenarios must not be empty"
            );
        }

        double initialValue =
                portfolioPricer.value(
                        portfolio,
                        initialState
                );

        double[] pnlDistribution =
                new double[scenarios.size()];

        for (int i = 0; i < scenarios.size(); i++) {

            SimulationScenario scenario =
                    Objects.requireNonNull(
                            scenarios.get(i),
                            "scenarios must not contain null"
                    );

            double futureValue =
                    portfolioPricer.value(
                            portfolio,
                            scenario.getTerminalState()
                    );

            pnlDistribution[i] =
                    futureValue - initialValue;
        }

        return pnlDistribution;
    }
}